### PR TITLE
s2568, ta 13133, issue #94 storage-inventory: add distinct(uri) to it…

### PR DESCRIPTION
**Pull request by hjeeves**
…erator query so duplicates avoided.

Fixes opencadc/storage-inventory#94

### CODE REVIEW

**Comment by hjeeves** [comment]
File with change was subject to ^M from my ide again (changed the line separator in a different place this time, hoping it takes.) . :(. The actual changed line where 'distinct' is added is highlighted in both the delete and the add (line 91.)

**Comment by hjeeves** [comment]
Still missing the iterator order test.

**Comment by hjeeves** [comment]
iterator test added, merged from master this morning (3/20, 8:30 am)

**Comment by pdowler** [comment]
The review comment above (mentioning StoredArtifactCompator) was misleading but the iterator test  did do the right thing (TreeSet of StorageMetadata since StorageMetadata implements Comparable).

**Pull request merged**
